# Generated by Django 4.1.1 on 2022-09-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_projectlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
