# Generated by Django 4.1.1 on 2022-09-19 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projectlist_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlist',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
