# Generated by Django 4.0 on 2022-01-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='experienceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position_name', models.CharField(max_length=200)),
                ('position_detail', models.TextField()),
                ('date_started', models.CharField(max_length=200)),
                ('date_ended', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='experienceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictures', models.ImageField(upload_to='experience/')),
                ('experience', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='exp_pics', to='experience.experiencelist')),
            ],
        ),
    ]
